### ISSUE TITLE
로그인 페이지 다크모드 구현

### ISSUE THREAD

**Issue by reflection1921** [reflection1921/KakaoStory-Enhanced#6]
- 로그인 페이지 다크모드 구현
  - 다만, 이는 다른 분께서 이미 구현해놓은 userscript가 있어 적용할지는 검토 중

**Comment by D3C4** [comment]
어차피 팔레트 스왑이고 기존에 사용하던 색상 있으니 이걸로 대체하기만 하면 될 것 같아 보여요

**Comment by reflection1921** [comment]
근데 다른 분께서 개발해두신게 있으니 내가 굳이 하나 더 만들어야하나 싶긴해
근데 그건 디스코드 다크는 아닌지라 또 고민되네

**Comment by reflection1921** [comment]
구현되어서 close 합니다
